// Copyright (c) 2023-present, Trail of Bits, Inc.

#ifndef MACRONI_DIALECT_MACRONI_IR_MACRONILEVELTYPES
#define MACRONI_DIALECT_MACRONI_IR_MACRONILEVELTYPES

include "mlir/Interfaces/DataLayoutInterfaces.td"
include "mlir/IR/SubElementInterfaces.td"
include "mlir/IR/BuiltinTypeInterfaces.td"

include "macroni/Dialect/Macroni/MacroniAttributes.td"

class WithDefaultDLTypeInterface { }

#endif // MACRONI_DIALECT_MACRONI_IR_MACRONILEVELTYPES
